### ISSUE TITLE
Link weekly issues together

### ISSUE THREAD

**Issue by multani** [bpmn-io/actions#12]
### Is your feature request related to a problem? Please describe.

It's easy to lose track of the previous discussion when the old weekly issue is closed and a new one created.

I'd like to have an easy way to link a new weekly issue to the previous weekly issue.

### Describe the solution you'd like

Support another template placeholder to interpolate the URL of the issue being closed.

See: https://docs.github.com/en/webhooks/webhook-events-and-payloads#issues

### Describe alternatives you've considered

Passing the template as a string instead of a file, so that we can do custom interpolation before the creation of the issue.

**Comment by barmac** [comment]
Hi,

isn't it sufficient that you can see a link from the previous weekly?

<img width="860" alt="image" src="https://github.com/bpmn-io/actions/assets/28307541/e192cdda-12f7-40d0-863d-4d0beac45750">

**Comment by multani** [comment]
It's possible to use this link, but it's not as visible as a dedicated place inside the issue body directly.
